<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Zt-WsEUNEeeJkrA3PIO9Tw" name="Example-CancelVacationRequest" version="1.5.0" author="antoine" bonitaVersion="7.10.3" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E33">
    <elements xmi:type="process:Pool" xmi:id="_Zt-WsUUNEeeJkrA3PIO9Tw" documentation="The process to cancel a vacation request. Request status need to be either approved or pending. Other status lead to an immediate end of the process with no actions. For request already approved a validation from the manager is required." name="Cancel Vacation Request" version="1.5.0" displayName="Cancel vacation request">
      <elements xmi:type="process:Lane" xmi:id="_Zt-WskUNEeeJkrA3PIO9Tw" documentation="Tasks performed by the user who is cancelling his vacation request." name="Requester lane" actor="_ZuAMK0UNEeeJkrA3PIO9Tw">
        <elements xmi:type="process:StartEvent" xmi:id="_Zt-Ws0UNEeeJkrA3PIO9Tw" name="Start" outgoing="_ZuAL7kUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-WtUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-WtkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-Wt0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Zt-WuEUNEeeJkrA3PIO9Tw" name="Vacation request status?" outgoing="_ZuAL8UUNEeeJkrA3PIO9Tw _ZuAMBEUNEeeJkrA3PIO9Tw _ZuAMB0UNEeeJkrA3PIO9Tw" incoming="_ZuAL7kUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-WukUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-Wu0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-WvEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_Zt-WvUUNEeeJkrA3PIO9Tw" name="Send message to cancel request" outgoing="_ZuAL9UUNEeeJkrA3PIO9Tw" incoming="_ZuAL8UUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-Wv0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-WwEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-WwUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_Zt-WwkUNEeeJkrA3PIO9Tw" documentation="Message to cancel a vacation request" name="cancellationMessage">
            <correlation xmi:type="process:Correlation" xmi:id="_Xruqskq2EeeZ-cvVQD6SQA" correlationType="KEYS">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_Xruqs0q2EeeZ-cvVQD6SQA">
                <expressions xmi:type="expression:ListExpression" xmi:id="_XruqtEq2EeeZ-cvVQD6SQA">
                  <expressions xmi:type="expression:Expression" xmi:id="_XruqtUq2EeeZ-cvVQD6SQA" name="requestId" content="requestId"/>
                  <expressions xmi:type="expression:Expression" xmi:id="_Xruqtkq2EeeZ-cvVQD6SQA" name="vacationRequestToCancel - com.company.model.VacationRequest#getPersistenceId" content="getPersistenceId" type="TYPE_JAVA_METHOD_CALL" returnType="java.lang.Long">
                    <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwW1WMNmEemUnogr5zNDiA" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                  </expressions>
                </expressions>
              </correlationAssociation>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_XruqsUq2EeeZ-cvVQD6SQA" name="New Vacation Request" content="New Vacation Request" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_XruqsEq2EeeZ-cvVQD6SQA" name="Catch cancellation message" content="Catch cancellation message" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_XrvRwEq2EeeZ-cvVQD6SQA"/>
          </events>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Zt-WzEUNEeeJkrA3PIO9Tw" name="Cancellation approved - yes - merge" outgoing="_ZuAMJUUNEeeJkrA3PIO9Tw" incoming="_ZuAL9UUNEeeJkrA3PIO9Tw _ZuAMH0UNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-WzkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-Wz0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-W0EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt-W0UUNEeeJkrA3PIO9Tw" name="Get vacation available" outgoing="_ZuAL-EUNEeeJkrA3PIO9Tw" incoming="_ZuAMJUUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-W00UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-9wEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-9wUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt-9wkUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt-9w0UNEeeJkrA3PIO9Tw" name="requesterVacationAvailable" content="requesterVacationAvailable" type="TYPE_VARIABLE" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDicNmEemUnogr5zNDiA" documentation="The counter of vacation day available for the user who is cancelling his request." name="requesterVacationAvailable" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt-9xUUNEeeJkrA3PIO9Tw" name="VacationAvailable.findByBonitaUserId" content="SELECT v&#xA;FROM VacationAvailable v&#xA;WHERE v.bonitaUserId= :bonitaUserId&#xA;" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="expression:Expression" xmi:id="_CDDmcNrhEemWoPaj1w4E3A" name="bonitaUserId" content="bonitaUserId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_CDDmcdrhEemWoPaj1w4E3A" name="processInstanceInitiator" content="BonitaUsers.getProcessInstanceInitiator(apiAccessor,processInstanceId).id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_CDDmctrhEemWoPaj1w4E3A" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_CDDmc9rhEemWoPaj1w4E3A" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </referencedElements>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Zt-9yUUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt-9ykUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt-9y0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt-9zEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt-9zUUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt-9zkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt-9z0UNEeeJkrA3PIO9Tw" name="Credit vacation available" outgoing="_ZuAL-0UNEeeJkrA3PIO9Tw" incoming="_ZuAL-EUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-90UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-90kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-900UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt-91EUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt-91UUNEeeJkrA3PIO9Tw" name="requesterVacationAvailable" content="requesterVacationAvailable" type="TYPE_VARIABLE" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDkMNmEemUnogr5zNDiA" documentation="The counter of vacation day available for the user who is cancelling his request." name="requesterVacationAvailable" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt-910UNEeeJkrA3PIO9Tw" name="resetVacationAvailable" content="requesterVacationAvailable.daysAvailableCounter +&#xD;&#xA;vacationRequestToCancel.numberOfDays" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDksNmEemUnogr5zNDiA" documentation="The counter of vacation day available for the user who is cancelling his request." name="requesterVacationAvailable" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDk8NmEemUnogr5zNDiA" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Zt-92kUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setDaysAvailableCounter">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt-920UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt-93EUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt-93UUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt-93kUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt-930UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt-94EUNEeeJkrA3PIO9Tw" name="Update vacation request status" outgoing="_ZuAL_kUNEeeJkrA3PIO9Tw" incoming="_ZuAL-0UNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-94kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-940UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-95EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt-95UUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt-95kUNEeeJkrA3PIO9Tw" name="vacationRequestToCancel" content="vacationRequestToCancel" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDlsNmEemUnogr5zNDiA" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt-96EUNEeeJkrA3PIO9Tw" name="cancelled" content="cancelled"/>
            <operator xmi:type="expression:Operator" xmi:id="_Zt-96UUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt-96kUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt-960UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt-97EUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt-97UUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt-97kUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Zt-970UNEeeJkrA3PIO9Tw" name="Vacation request status - merge" outgoing="_ZuAMAUUNEeeJkrA3PIO9Tw" incoming="_ZuAMBEUNEeeJkrA3PIO9Tw _ZuAMGUUNEeeJkrA3PIO9Tw _ZuAMKEUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-98UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-98kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-980UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Zt-99EUNEeeJkrA3PIO9Tw" name="End" incoming="_ZuAMAUUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-99kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-990UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-9-EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt-9-UUNEeeJkrA3PIO9Tw" name="Set vacation request status to &quot;processing cancellation&quot;" outgoing="_ZuAMC0UNEeeJkrA3PIO9Tw" incoming="_ZuAMB0UNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt-9-0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt-9_EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt-9_UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt-9_kUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt-9_0UNEeeJkrA3PIO9Tw" name="vacationRequestToCancel" content="vacationRequestToCancel" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYDmsNmEemUnogr5zNDiA" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--AUUNEeeJkrA3PIO9Tw" name="processing cancellation" content="processing cancellation"/>
            <operator xmi:type="expression:Operator" xmi:id="_Zt--AkUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt--A0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt--BEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt--BUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt--BkUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt--B0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt--CEUNEeeJkrA3PIO9Tw" name="Notify manager cancellation request to review" outgoing="_ZuAMHEUNEeeJkrA3PIO9Tw" incoming="_ZuAMC0UNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt--CkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt--C0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt--DEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Zt--DUUNEeeJkrA3PIO9Tw" name="emailNotifyManagerCancellationToReview" definitionId="email" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Zt--DkUNEeeJkrA3PIO9Tw" definitionId="email" version="1.1.0" modelVersion="7.1.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--D0UNEeeJkrA3PIO9Tw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--EEUNEeeJkrA3PIO9Tw" name="emailServerAddress" content="emailServerAddress" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--EUUNEeeJkrA3PIO9Tw" name="emailServerAddress" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--EkUNEeeJkrA3PIO9Tw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--E0UNEeeJkrA3PIO9Tw" name="emailServerPort" content="emailServerPort" type="TYPE_PARAMETER" returnType="java.lang.Integer" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--FEUNEeeJkrA3PIO9Tw" name="emailServerPort" typeClassname="java.lang.Integer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--FUUNEeeJkrA3PIO9Tw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--FkUNEeeJkrA3PIO9Tw" name="emailServerUseSSL" content="emailServerUseSSL" type="TYPE_PARAMETER" returnType="java.lang.Boolean" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--F0UNEeeJkrA3PIO9Tw" name="emailServerUseSSL" typeClassname="java.lang.Boolean"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--GEUNEeeJkrA3PIO9Tw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--GUUNEeeJkrA3PIO9Tw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--GkUNEeeJkrA3PIO9Tw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--G0UNEeeJkrA3PIO9Tw" name="emailServerUsername" content="emailServerUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--HEUNEeeJkrA3PIO9Tw" name="emailServerUsername" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--HUUNEeeJkrA3PIO9Tw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--HkUNEeeJkrA3PIO9Tw" name="emailServerPassword" content="emailServerPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--H0UNEeeJkrA3PIO9Tw" name="emailServerPassword" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--IEUNEeeJkrA3PIO9Tw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--IUUNEeeJkrA3PIO9Tw" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--IkUNEeeJkrA3PIO9Tw" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--I0UNEeeJkrA3PIO9Tw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--JEUNEeeJkrA3PIO9Tw" name="searchReviewerEmailAddress" content="import org.bonitasoft.engine.identity.ContactData&#xD;&#xA;import org.bonitasoft.engine.identity.User&#xD;&#xA;&#xD;&#xA;User requestorUserInfo =&#xD;&#xA; BonitaUsers.getUser(apiAccessor,&#xD;&#xA;  vacationRequestToCancel.requesterBonitaUserId)&#xD;&#xA;&#xD;&#xA;ContactData managerProfessionalContactInfo =&#xD;&#xA; BonitaUsers.getUserProfessionalContactInfo(apiAccessor,&#xD;&#xA;  requestorUserInfo.managerUserId)&#xD;&#xA;&#xD;&#xA;return managerProfessionalContactInfo.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QC4h4NriEemWoPaj1w4E3A" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Zt--JUUNEeeJkrA3PIO9Tw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--JkUNEeeJkrA3PIO9Tw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--J0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--KEUNEeeJkrA3PIO9Tw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--KUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--KkUNEeeJkrA3PIO9Tw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--K0UNEeeJkrA3PIO9Tw" name="Vacation cancellation request to review" content="Vacation cancellation request to review" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--LEUNEeeJkrA3PIO9Tw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--LUUNEeeJkrA3PIO9Tw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--LkUNEeeJkrA3PIO9Tw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--L0UNEeeJkrA3PIO9Tw" name="&lt;pattern-expression>" content="Please go to the Tahiti application and review this cancellation request from a member of your team." type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--MEUNEeeJkrA3PIO9Tw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Zt--MUUNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--MkUNEeeJkrA3PIO9Tw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--M0UNEeeJkrA3PIO9Tw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--NEUNEeeJkrA3PIO9Tw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--NUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--NkUNEeeJkrA3PIO9Tw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Zt--N0UNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yluOrWeUEeqLtoKXrpaKXg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_ylu1ameUEeqLtoKXrpaKXg" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_ylu1a2eUEeqLtoKXrpaKXg" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt--OEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt--OUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt--OkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt--O0UNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt--PEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt--PUUNEeeJkrA3PIO9Tw" name="Update calendar request cancelled" outgoing="_ZuAMKEUNEeeJkrA3PIO9Tw" incoming="_ZuAL_kUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt--P0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt--QEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt--QUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Zt--QkUNEeeJkrA3PIO9Tw" name="calRemoveCancellededVacationEvent" definitionId="google-calendar-v3-delete-event" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Zt--Q0UNEeeJkrA3PIO9Tw" definitionId="google-calendar-v3-delete-event" version="1.0.0" modelVersion="7.1.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--REUNEeeJkrA3PIO9Tw" key="applicationName">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--RUUNEeeJkrA3PIO9Tw" name="calendarApplicationName" content="calendarApplicationName" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--RkUNEeeJkrA3PIO9Tw" name="calendarApplicationName" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--R0UNEeeJkrA3PIO9Tw" key="serviceAccountId">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--SEUNEeeJkrA3PIO9Tw" name="calendarServiceAccountId" content="calendarServiceAccountId" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--SUUNEeeJkrA3PIO9Tw" name="calendarServiceAccountId" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--SkUNEeeJkrA3PIO9Tw" key="serviceAccountP12File">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--S0UNEeeJkrA3PIO9Tw" name="calendarServiceAccountP12File" content="calendarServiceAccountP12File" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--TEUNEeeJkrA3PIO9Tw" name="calendarServiceAccountP12File" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--TUUNEeeJkrA3PIO9Tw" key="serviceAccountUser">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--TkUNEeeJkrA3PIO9Tw" name="calendarServiceAccountUser" content="calendarServiceAccountUser" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--T0UNEeeJkrA3PIO9Tw" name="calendarServiceAccountUser" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--UEUNEeeJkrA3PIO9Tw" key="calendarId">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--UUUNEeeJkrA3PIO9Tw" name="calendarCalendarId" content="calendarCalendarId" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt--UkUNEeeJkrA3PIO9Tw" name="calendarCalendarId" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--U0UNEeeJkrA3PIO9Tw" key="sendNotifications">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--VEUNEeeJkrA3PIO9Tw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--VUUNEeeJkrA3PIO9Tw" key="maxAttendees">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--VkUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--V0UNEeeJkrA3PIO9Tw" key="prettyPrint">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--WEUNEeeJkrA3PIO9Tw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt--WUUNEeeJkrA3PIO9Tw" key="id">
                <expression xmi:type="expression:Expression" xmi:id="_Zt--WkUNEeeJkrA3PIO9Tw" name="vacationRequestToCancel - com.company.model.VacationRequest#getCalendarEventId" content="getCalendarEventId" type="TYPE_JAVA_METHOD_CALL" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwZ4wcNmEemUnogr5zNDiA" name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--XEUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--XUUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--XkUNEeeJkrA3PIO9Tw" name="event" content="event" type="CONNECTOR_OUTPUT_TYPE" returnType="com.google.api.services.calendar.model.Event">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--X0UNEeeJkrA3PIO9Tw" name="event" type="com.google.api.services.calendar.model.Event"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--YEUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--YUUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--YkUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--Y0UNEeeJkrA3PIO9Tw" name="etag" content="etag" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--ZEUNEeeJkrA3PIO9Tw" name="etag" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--ZUUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--ZkUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--Z0UNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--aEUNEeeJkrA3PIO9Tw" name="hangoutLink" content="hangoutLink" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--aUUNEeeJkrA3PIO9Tw" name="hangoutLink" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--akUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--a0UNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--bEUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--bUUNEeeJkrA3PIO9Tw" name="htmlLink" content="htmlLink" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--bkUNEeeJkrA3PIO9Tw" name="htmlLink" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--b0UNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--cEUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--cUUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--ckUNEeeJkrA3PIO9Tw" name="iCalUID" content="iCalUID" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--c0UNEeeJkrA3PIO9Tw" name="iCalUID" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--dEUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--dUUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--dkUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--d0UNEeeJkrA3PIO9Tw" name="id" content="id" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--eEUNEeeJkrA3PIO9Tw" name="id" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--eUUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--ekUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--e0UNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--fEUNEeeJkrA3PIO9Tw" name="status" content="status" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--fUUNEeeJkrA3PIO9Tw" name="status" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--fkUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--f0UNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--gEUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--gUUNEeeJkrA3PIO9Tw" name="summary" content="summary" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--gkUNEeeJkrA3PIO9Tw" name="summary" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--g0UNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--hEUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--hUUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--hkUNEeeJkrA3PIO9Tw" name="description" content="description" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--h0UNEeeJkrA3PIO9Tw" name="description" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--iEUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--iUUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--ikUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--i0UNEeeJkrA3PIO9Tw" name="location" content="location" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--jEUNEeeJkrA3PIO9Tw" name="location" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--jUUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--jkUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--j0UNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--kEUNEeeJkrA3PIO9Tw" name="transparency" content="transparency" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--kUUNEeeJkrA3PIO9Tw" name="transparency" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--kkUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--k0UNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--lEUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--lUUNEeeJkrA3PIO9Tw" name="visibility" content="visibility" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--lkUNEeeJkrA3PIO9Tw" name="visibility" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--l0UNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--mEUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--mUUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--mkUNEeeJkrA3PIO9Tw" name="sequence" content="sequence" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--m0UNEeeJkrA3PIO9Tw" name="sequence" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--nEUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--nUUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--nkUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--n0UNEeeJkrA3PIO9Tw" name="anyoneCanAddSelf" content="anyoneCanAddSelf" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--oEUNEeeJkrA3PIO9Tw" name="anyoneCanAddSelf" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--oUUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--okUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--o0UNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--pEUNEeeJkrA3PIO9Tw" name="guestsCanInviteOthers" content="guestsCanInviteOthers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--pUUNEeeJkrA3PIO9Tw" name="guestsCanInviteOthers" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt--pkUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt--p0UNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt--qEUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt--qUUNEeeJkrA3PIO9Tw" name="guestsCanModify" content="guestsCanModify" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt--qkUNEeeJkrA3PIO9Tw" name="guestsCanModify" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt_k0EUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Zt_k0UUNEeeJkrA3PIO9Tw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Zt_k0kUNEeeJkrA3PIO9Tw" content=""/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Zt_k00UNEeeJkrA3PIO9Tw" name="guestsCanSeeOtherGuests" content="guestsCanSeeOtherGuests" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_Zt_k1EUNEeeJkrA3PIO9Tw" name="guestsCanSeeOtherGuests" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Zt_k1UUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt_k1kUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt_k10UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt_k2EUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt_k2UUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt_k2kUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Zt_k20UNEeeJkrA3PIO9Tw" documentation="Tasks performed by the manager of the user who is cancelling his vacation request." name="Manager lane" actor="_YV8rcNq6EemWoPaj1w4E3A">
        <elements xmi:type="process:Task" xmi:id="_Zt_k3EUNEeeJkrA3PIO9Tw" name="Review cancellation" outgoing="_ZuAMDkUNEeeJkrA3PIO9Tw" incoming="_ZuAMHEUNEeeJkrA3PIO9Tw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt_k3kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt_k30UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt_k4EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt_k4UUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt_k4kUNEeeJkrA3PIO9Tw" name="cancellationApproved" content="cancellationApproved" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_PwbGxMNmEemUnogr5zNDiA" documentation="Decision of the manager to approve or reject cancellation of an already approved request. We use a process variable as this information is only relevant in the context of this process instance. Manager choice will lead to an update of request status." name="cancellationApproved" dataType="_ZuAMSkUNEeeJkrA3PIO9Tw"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt_k5EUNEeeJkrA3PIO9Tw" name="cancellationApprovedContract" content="cancellationApprovedContract" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PwbGxsNmEemUnogr5zNDiA" name="cancellationApprovedContract" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_PwbG0sNmEemUnogr5zNDiA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Zt_k50UNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt_k6EUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt_k6UUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt_k6kUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt_k60UNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt_k7EUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Zt_k70UNEeeJkrA3PIO9Tw">
            <targetForm xmi:type="expression:Expression" xmi:id="_Zt_k8EUNEeeJkrA3PIO9Tw" name="cancellationReviewForm" content="f8fbd7dc-00ff-463f-90e8-e9fd197b71ce" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Zt_k9UUNEeeJkrA3PIO9Tw">
            <inputs xmi:type="process:ContractInput" xmi:id="_Zt_k9kUNEeeJkrA3PIO9Tw" name="cancellationApprovedContract" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_Zt_k90UNEeeJkrA3PIO9Tw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Zt_k-EUNEeeJkrA3PIO9Tw" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Zt_k-UUNEeeJkrA3PIO9Tw" name="Cancellation approved?" outgoing="_ZuAMEUUNEeeJkrA3PIO9Tw _ZuAMFkUNEeeJkrA3PIO9Tw" incoming="_ZuAMDkUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt_k-0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt_k_EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt_k_UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt_k_kUNEeeJkrA3PIO9Tw" name="Reset vacation request status to approved" outgoing="_ZuAMGUUNEeeJkrA3PIO9Tw" incoming="_ZuAMIkUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt_lAEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt_lAUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt_lAkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Zt_lA0UNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Zt_lBEUNEeeJkrA3PIO9Tw" name="vacationRequestToCancel" content="vacationRequestToCancel" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PwYqgcNmEemUnogr5zNDiA" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Zt_lBkUNEeeJkrA3PIO9Tw" name="approved" content="approved"/>
            <operator xmi:type="expression:Operator" xmi:id="_Zt_lB0UNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt_lCEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt_lCUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt_lCkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt_lC0UNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt_lDEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt_lDUUNEeeJkrA3PIO9Tw" name="Notify employee cancellation approved" outgoing="_ZuAMH0UNEeeJkrA3PIO9Tw" incoming="_ZuAMEUUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt_lD0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt_lEEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt_lEUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Zt_lEkUNEeeJkrA3PIO9Tw" name="emailNotifyEmployeeCancellationApproved" definitionId="email" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Zt_lE0UNEeeJkrA3PIO9Tw" definitionId="email" version="1.1.0" modelVersion="7.1.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lFEUNEeeJkrA3PIO9Tw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lFUUNEeeJkrA3PIO9Tw" name="emailServerAddress" content="emailServerAddress" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lFkUNEeeJkrA3PIO9Tw" name="emailServerAddress" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lF0UNEeeJkrA3PIO9Tw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lGEUNEeeJkrA3PIO9Tw" name="emailServerPort" content="emailServerPort" type="TYPE_PARAMETER" returnType="java.lang.Integer" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lGUUNEeeJkrA3PIO9Tw" name="emailServerPort" typeClassname="java.lang.Integer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lGkUNEeeJkrA3PIO9Tw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lG0UNEeeJkrA3PIO9Tw" name="emailServerUseSSL" content="emailServerUseSSL" type="TYPE_PARAMETER" returnType="java.lang.Boolean" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lHEUNEeeJkrA3PIO9Tw" name="emailServerUseSSL" typeClassname="java.lang.Boolean"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lHUUNEeeJkrA3PIO9Tw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lHkUNEeeJkrA3PIO9Tw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lH0UNEeeJkrA3PIO9Tw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lIEUNEeeJkrA3PIO9Tw" name="emailServerUsername" content="emailServerUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lIUUNEeeJkrA3PIO9Tw" name="emailServerUsername" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lIkUNEeeJkrA3PIO9Tw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lI0UNEeeJkrA3PIO9Tw" name="emailServerPassword" content="emailServerPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lJEUNEeeJkrA3PIO9Tw" name="emailServerPassword" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lJUUNEeeJkrA3PIO9Tw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lJkUNEeeJkrA3PIO9Tw" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lJ0UNEeeJkrA3PIO9Tw" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lKEUNEeeJkrA3PIO9Tw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lKUUNEeeJkrA3PIO9Tw" name="findRequestorEmailAddress" content="return BonitaUsers.getProcessInstanceInitiatorProfessionalContactInfo(&#xD;&#xA; apiAccessor, processInstanceId).email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Zt_lKkUNEeeJkrA3PIO9Tw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Zt_lK0UNEeeJkrA3PIO9Tw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lLEUNEeeJkrA3PIO9Tw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lLUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lLkUNEeeJkrA3PIO9Tw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lL0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lMEUNEeeJkrA3PIO9Tw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lMUUNEeeJkrA3PIO9Tw" name="Your vacation cancellation request has been approved" content="Your vacation cancellation request has been approved" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lMkUNEeeJkrA3PIO9Tw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lM0UNEeeJkrA3PIO9Tw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lNEUNEeeJkrA3PIO9Tw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lNUUNEeeJkrA3PIO9Tw" name="&lt;pattern-expression>" content="Your manager has approved your vacation cancellation request." type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lNkUNEeeJkrA3PIO9Tw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Zt_lN0UNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lOEUNEeeJkrA3PIO9Tw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lOUUNEeeJkrA3PIO9Tw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lOkUNEeeJkrA3PIO9Tw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lO0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lPEUNEeeJkrA3PIO9Tw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Zt_lPUUNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yluOyGeUEeqLtoKXrpaKXg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_ylu1bGeUEeqLtoKXrpaKXg" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_ylu1bWeUEeqLtoKXrpaKXg" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt_lPkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt_lP0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt_lQEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt_lQUUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt_lQkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zt_lQ0UNEeeJkrA3PIO9Tw" name="Notify employee cancellation refused" outgoing="_ZuAMIkUNEeeJkrA3PIO9Tw" incoming="_ZuAMFkUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zt_lRUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zt_lRkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zt_lR0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Zt_lSEUNEeeJkrA3PIO9Tw" name="emailNotifyEmployeeCancellationRefused" definitionId="email" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Zt_lSUUNEeeJkrA3PIO9Tw" definitionId="email" version="1.1.0" modelVersion="7.1.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lSkUNEeeJkrA3PIO9Tw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lS0UNEeeJkrA3PIO9Tw" name="emailServerAddress" content="emailServerAddress" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lTEUNEeeJkrA3PIO9Tw" name="emailServerAddress" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lTUUNEeeJkrA3PIO9Tw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lTkUNEeeJkrA3PIO9Tw" name="emailServerPort" content="emailServerPort" type="TYPE_PARAMETER" returnType="java.lang.Integer" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lT0UNEeeJkrA3PIO9Tw" name="emailServerPort" typeClassname="java.lang.Integer"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lUEUNEeeJkrA3PIO9Tw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lUUUNEeeJkrA3PIO9Tw" name="emailServerUseSSL" content="emailServerUseSSL" type="TYPE_PARAMETER" returnType="java.lang.Boolean" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lUkUNEeeJkrA3PIO9Tw" name="emailServerUseSSL" typeClassname="java.lang.Boolean"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lU0UNEeeJkrA3PIO9Tw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lVEUNEeeJkrA3PIO9Tw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lVUUNEeeJkrA3PIO9Tw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lVkUNEeeJkrA3PIO9Tw" name="emailServerUsername" content="emailServerUsername" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lV0UNEeeJkrA3PIO9Tw" name="emailServerUsername" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lWEUNEeeJkrA3PIO9Tw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lWUUNEeeJkrA3PIO9Tw" name="emailServerPassword" content="emailServerPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lWkUNEeeJkrA3PIO9Tw" name="emailServerPassword" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lW0UNEeeJkrA3PIO9Tw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lXEUNEeeJkrA3PIO9Tw" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_Zt_lXUUNEeeJkrA3PIO9Tw" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lXkUNEeeJkrA3PIO9Tw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lX0UNEeeJkrA3PIO9Tw" name="findRequestorEmailAddress" content="return BonitaUsers.getProcessInstanceInitiatorProfessionalContactInfo(&#xD;&#xA; apiAccessor, processInstanceId).email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Zt_lYEUNEeeJkrA3PIO9Tw" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Zt_lYUUNEeeJkrA3PIO9Tw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lYkUNEeeJkrA3PIO9Tw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lY0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lZEUNEeeJkrA3PIO9Tw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lZUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lZkUNEeeJkrA3PIO9Tw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lZ0UNEeeJkrA3PIO9Tw" name="Your vacation cancellation request has been refused" content="Your vacation cancellation request has been refused" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_laEUNEeeJkrA3PIO9Tw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_laUUNEeeJkrA3PIO9Tw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lakUNEeeJkrA3PIO9Tw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_la0UNEeeJkrA3PIO9Tw" name="&lt;pattern-expression>" content="Your manager has refused your vacation cancellation request. Please discuss this with your manager." type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lbEUNEeeJkrA3PIO9Tw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Zt_lbUUNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lbkUNEeeJkrA3PIO9Tw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lb0UNEeeJkrA3PIO9Tw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lcEUNEeeJkrA3PIO9Tw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Zt_lcUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Zt_lckUNEeeJkrA3PIO9Tw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Zt_lc0UNEeeJkrA3PIO9Tw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yluO2meUEeqLtoKXrpaKXg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_ylu1bmeUEeqLtoKXrpaKXg" name="emailNotificationSender" content="emailNotificationSender" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_ylu1b2eUEeqLtoKXrpaKXg" name="emailNotificationSender" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zt_ldEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zt_ldUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zt_ldkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zt_ld0UNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zt_leEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_HDcMYNq7EemWoPaj1w4E3A" documentation="Task in this lane need to be available only for the manager of the requester" name="cancellationRequesterManager" definitionId="initiator-manager" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_HDcMYdq7EemWoPaj1w4E3A" definitionId="initiator-manager" version="1.0.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HDczcNq7EemWoPaj1w4E3A" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_HDczcdq7EemWoPaj1w4E3A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <data xmi:type="process:Data" xmi:id="_Zt_le0UNEeeJkrA3PIO9Tw" documentation="Decision of the manager to approve or reject cancellation of an already approved request. We use a process variable as this information is only relevant in the context of this process instance. Manager choice will lead to an update of request status." name="cancellationApproved" dataType="_ZuAMSkUNEeeJkrA3PIO9Tw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Zt_lfEUNEeeJkrA3PIO9Tw" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Zt_lfUUNEeeJkrA3PIO9Tw" documentation="The vacation the user want to cancel. The process start with the persitence id of the vacation request to cancel (see contract). The default value of this variable is set by searching the matching request." name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest">
        <defaultValue xmi:type="expression:Expression" xmi:id="_apQVEEthEeey8-nS6o05Dw" name="VacationRequest.findByPersistenceId" content="SELECT v&#xA;FROM VacationRequest v&#xA;WHERE v.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.VacationRequest">
          <referencedElements xmi:type="expression:Expression" xmi:id="_yKLwcNq4EemWoPaj1w4E3A" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_yKLwcdq4EemWoPaj1w4E3A" name="toLongValue" content="// Due to number limitation in JavaScript id is received as a String and convert to a Java Long value&#xA;Long.valueOf(vacationRequestIdContract)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yKLwctq4EemWoPaj1w4E3A" name="vacationRequestIdContract" description="The id of the vacation request to be cancelled.">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_yKLwc9q4EemWoPaj1w4E3A"/>
              </referencedElements>
            </referencedElements>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ZuAL5EUNEeeJkrA3PIO9Tw" documentation="The counter of vacation day available for the user who is cancelling his request." name="requesterVacationAvailable" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ZuAL5UUNEeeJkrA3PIO9Tw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ZuAL6EUNEeeJkrA3PIO9Tw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZuAL6UUNEeeJkrA3PIO9Tw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ZuAL60UNEeeJkrA3PIO9Tw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZuAL7EUNEeeJkrA3PIO9Tw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL7kUNEeeJkrA3PIO9Tw" target="_Zt-WuEUNEeeJkrA3PIO9Tw" source="_Zt-Ws0UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL70UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAL8EUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL8UUNEeeJkrA3PIO9Tw" name="Pending" target="_Zt-WvUUNEeeJkrA3PIO9Tw" source="_Zt-WuEUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL8kUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAL80UNEeeJkrA3PIO9Tw" name="isRequestStatusPending" content="return vacationRequestToCancel.status == &quot;pending&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pwbt0sNmEemUnogr5zNDiA" name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL9UUNEeeJkrA3PIO9Tw" target="_Zt-WzEUNEeeJkrA3PIO9Tw" source="_Zt-WvUUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL9kUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAL90UNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL-EUNEeeJkrA3PIO9Tw" target="_Zt-9z0UNEeeJkrA3PIO9Tw" source="_Zt-W0UUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL-UUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAL-kUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL-0UNEeeJkrA3PIO9Tw" target="_Zt-94EUNEeeJkrA3PIO9Tw" source="_Zt-9z0UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL_EUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAL_UUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAL_kUNEeeJkrA3PIO9Tw" target="_Zt--PUUNEeeJkrA3PIO9Tw" source="_Zt-94EUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAL_0UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMAEUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMAUUNEeeJkrA3PIO9Tw" target="_Zt-99EUNEeeJkrA3PIO9Tw" source="_Zt-970UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMAkUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMA0UNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMBEUNEeeJkrA3PIO9Tw" name="Default" target="_Zt-970UNEeeJkrA3PIO9Tw" source="_Zt-WuEUNEeeJkrA3PIO9Tw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMBUUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMBkUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMB0UNEeeJkrA3PIO9Tw" name="Approved" target="_Zt-9-UUNEeeJkrA3PIO9Tw" source="_Zt-WuEUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMCEUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMCUUNEeeJkrA3PIO9Tw" name="isRequestStatusApproved" content="return vacationRequestToCancel.status == &quot;approved&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Pwbt4cNmEemUnogr5zNDiA" name="vacationRequestToCancel" dataType="_ZuAMUkUNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMC0UNEeeJkrA3PIO9Tw" target="_Zt--CEUNEeeJkrA3PIO9Tw" source="_Zt-9-UUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMDEUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMDUUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMDkUNEeeJkrA3PIO9Tw" target="_Zt_k-UUNEeeJkrA3PIO9Tw" source="_Zt_k3EUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMD0UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMEEUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMEUUNEeeJkrA3PIO9Tw" name="Yes" target="_Zt_lDUUNEeeJkrA3PIO9Tw" source="_Zt_k-UUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMEkUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAME0UNEeeJkrA3PIO9Tw" name="cancellationApproved" content="cancellationApproved" interpreter="GROOVY" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Pwbt6MNmEemUnogr5zNDiA" documentation="Decision of the manager to approve or reject cancellation of an already approved request. We use a process variable as this information is only relevant in the context of this process instance. Manager choice will lead to an update of request status." name="cancellationApproved" dataType="_ZuAMSkUNEeeJkrA3PIO9Tw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMFkUNEeeJkrA3PIO9Tw" name="No" target="_Zt_lQ0UNEeeJkrA3PIO9Tw" source="_Zt_k-UUNEeeJkrA3PIO9Tw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMF0UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMGEUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMGUUNEeeJkrA3PIO9Tw" target="_Zt-970UNEeeJkrA3PIO9Tw" source="_Zt_k_kUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMGkUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMG0UNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMHEUNEeeJkrA3PIO9Tw" target="_Zt_k3EUNEeeJkrA3PIO9Tw" source="_Zt--CEUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMHUUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMHkUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMH0UNEeeJkrA3PIO9Tw" target="_Zt-WzEUNEeeJkrA3PIO9Tw" source="_Zt_lDUUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMIEUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMIUUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMIkUNEeeJkrA3PIO9Tw" target="_Zt_k_kUNEeeJkrA3PIO9Tw" source="_Zt_lQ0UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMI0UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMJEUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMJUUNEeeJkrA3PIO9Tw" target="_Zt-W0UUNEeeJkrA3PIO9Tw" source="_Zt-WzEUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMJkUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMJ0UNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZuAMKEUNEeeJkrA3PIO9Tw" target="_Zt-970UNEeeJkrA3PIO9Tw" source="_Zt--PUUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZuAMKUUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZuAMKkUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_ZuAMK0UNEeeJkrA3PIO9Tw" documentation="Actor who is cancelling his vacation request. Only used to defined who can start the process." name="Requester actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_YV8rcNq6EemWoPaj1w4E3A" documentation="Manager of the user who is cancelling his vacation request. Actor is actually override by an actor filter that find manager of the requester." name="Manager actor"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMLEUNEeeJkrA3PIO9Tw" name="emailServerAddress" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMLUUNEeeJkrA3PIO9Tw" name="emailServerPassword" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMLkUNEeeJkrA3PIO9Tw" name="emailServerPort" typeClassname="java.lang.Integer"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAML0UNEeeJkrA3PIO9Tw" name="emailServerUsername" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMMEUNEeeJkrA3PIO9Tw" name="emailServerUseSSL" typeClassname="java.lang.Boolean"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMMUUNEeeJkrA3PIO9Tw" name="emailNotificationSender" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMMkUNEeeJkrA3PIO9Tw" name="emailHRAddress" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMM0UNEeeJkrA3PIO9Tw" name="calendarApplicationName" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMNEUNEeeJkrA3PIO9Tw" name="calendarCalendarId" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMNUUNEeeJkrA3PIO9Tw" name="calendarServiceAccountId" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMNkUNEeeJkrA3PIO9Tw" name="calendarServiceAccountP12File" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ZuAMN0UNEeeJkrA3PIO9Tw" name="calendarServiceAccountUser" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_ZuAMOEUNEeeJkrA3PIO9Tw">
        <inputs xmi:type="process:ContractInput" xmi:id="_ZuAMOUUNEeeJkrA3PIO9Tw" name="vacationRequestIdContract" description="The id of the vacation request to be cancelled.">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_ZuAMOkUNEeeJkrA3PIO9Tw"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZuAMO0UNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_ZuAMPEUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZuAMPUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZuAMPkUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_ZuAMP0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZuAMQEUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZuAMQUUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_ZuAMQkUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZuAMQ0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZuAMREUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_ZuAMRUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZuAMRkUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZuAMR0UNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_ZuAMSEUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZuAMSUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_ZuAMSkUNEeeJkrA3PIO9Tw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_ZuAMS0UNEeeJkrA3PIO9Tw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_ZuAMTEUNEeeJkrA3PIO9Tw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_ZuAMTUUNEeeJkrA3PIO9Tw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_ZuAMTkUNEeeJkrA3PIO9Tw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_ZuAMT0UNEeeJkrA3PIO9Tw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_ZuAMUEUNEeeJkrA3PIO9Tw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_ZuAMUUUNEeeJkrA3PIO9Tw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_ZuAMUkUNEeeJkrA3PIO9Tw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_ZuAMU0UNEeeJkrA3PIO9Tw" type="Process" element="_Zt-WsEUNEeeJkrA3PIO9Tw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_ZuAMVEUNEeeJkrA3PIO9Tw" type="2007" element="_Zt-WsUUNEeeJkrA3PIO9Tw">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMVUUNEeeJkrA3PIO9Tw" type="5008" element="_Zt-WsUUNEeeJkrA3PIO9Tw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMVkUNEeeJkrA3PIO9Tw" type="7001" element="_Zt-WsUUNEeeJkrA3PIO9Tw">
        <children xmi:type="notation:Node" xmi:id="_ZuAMV0UNEeeJkrA3PIO9Tw" type="3007" element="_Zt-WskUNEeeJkrA3PIO9Tw">
          <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMWEUNEeeJkrA3PIO9Tw" type="5007" element="_Zt-WskUNEeeJkrA3PIO9Tw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMWUUNEeeJkrA3PIO9Tw" type="7002" element="_Zt-WskUNEeeJkrA3PIO9Tw">
            <children xmi:type="notation:Shape" xmi:id="_ZuAMWkUNEeeJkrA3PIO9Tw" type="3002" element="_Zt-Ws0UNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMW0UNEeeJkrA3PIO9Tw" visible="false" type="5024" element="_Zt-Ws0UNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMXEUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMXUUNEeeJkrA3PIO9Tw" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMXkUNEeeJkrA3PIO9Tw" type="3008" element="_Zt-WuEUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMX0UNEeeJkrA3PIO9Tw" visible="false" type="5026" element="_Zt-WuEUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMYEUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMYUUNEeeJkrA3PIO9Tw" x="138" y="61" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMYkUNEeeJkrA3PIO9Tw" type="3014" element="_Zt-WvUUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMY0UNEeeJkrA3PIO9Tw" type="5030" element="_Zt-WvUUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMZEUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMZUUNEeeJkrA3PIO9Tw" x="252" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMZkUNEeeJkrA3PIO9Tw" type="3008" element="_Zt-WzEUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMZ0UNEeeJkrA3PIO9Tw" visible="false" type="5026" element="_Zt-WzEUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMaEUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMaUUNEeeJkrA3PIO9Tw" x="347" y="61" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMakUNEeeJkrA3PIO9Tw" type="3027" element="_Zt-W0UUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMa0UNEeeJkrA3PIO9Tw" type="5017" element="_Zt-W0UUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMbEUNEeeJkrA3PIO9Tw" x="423" y="55" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMbUUNEeeJkrA3PIO9Tw" type="3027" element="_Zt-9z0UNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMbkUNEeeJkrA3PIO9Tw" type="5017" element="_Zt-9z0UNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMb0UNEeeJkrA3PIO9Tw" x="575" y="55" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMcEUNEeeJkrA3PIO9Tw" type="3027" element="_Zt-94EUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMcUUNEeeJkrA3PIO9Tw" type="5017" element="_Zt-94EUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMckUNEeeJkrA3PIO9Tw" x="710" y="55" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMc0UNEeeJkrA3PIO9Tw" type="3008" element="_Zt-970UNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMdEUNEeeJkrA3PIO9Tw" visible="false" type="5026" element="_Zt-970UNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMdUUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMdkUNEeeJkrA3PIO9Tw" x="1012" y="61" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMd0UNEeeJkrA3PIO9Tw" type="3003" element="_Zt-99EUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMeEUNEeeJkrA3PIO9Tw" visible="false" type="5025" element="_Zt-99EUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAMeUUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMekUNEeeJkrA3PIO9Tw" x="1088" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAMe0UNEeeJkrA3PIO9Tw" type="3027" element="_Zt-9-UUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAMfEUNEeeJkrA3PIO9Tw" type="5017" element="_Zt-9-UUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAMfUUNEeeJkrA3PIO9Tw" x="81" y="160" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAy8EUNEeeJkrA3PIO9Tw" type="3027" element="_Zt--CEUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAy8UUNEeeJkrA3PIO9Tw" type="5017" element="_Zt--CEUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAy8kUNEeeJkrA3PIO9Tw" x="90" y="290" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAy80UNEeeJkrA3PIO9Tw" type="3027" element="_Zt--PUUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAy9EUNEeeJkrA3PIO9Tw" type="5017" element="_Zt--PUUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAy9UUNEeeJkrA3PIO9Tw" x="860" y="50" width="132" height="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZuAy9kUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ZuAy90UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ZuAy-EUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ZuAy-UUNEeeJkrA3PIO9Tw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAy-kUNEeeJkrA3PIO9Tw" x="45" y="10" width="1358" height="435"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ZuAy-0UNEeeJkrA3PIO9Tw" type="3007" element="_Zt_k20UNEeeJkrA3PIO9Tw">
          <children xmi:type="notation:DecorationNode" xmi:id="_ZuAy_EUNEeeJkrA3PIO9Tw" type="5007" element="_Zt_k20UNEeeJkrA3PIO9Tw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ZuAy_UUNEeeJkrA3PIO9Tw" type="7002" element="_Zt_k20UNEeeJkrA3PIO9Tw">
            <children xmi:type="notation:Shape" xmi:id="_ZuAy_kUNEeeJkrA3PIO9Tw" type="3005" element="_Zt_k3EUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAy_0UNEeeJkrA3PIO9Tw" type="5005" element="_Zt_k3EUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzAEUNEeeJkrA3PIO9Tw" x="91" y="124" width="136" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAzAUUNEeeJkrA3PIO9Tw" type="3008" element="_Zt_k-UUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzAkUNEeeJkrA3PIO9Tw" type="5026" element="_Zt_k-UUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzA0UNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzBEUNEeeJkrA3PIO9Tw" x="347" y="136" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAzBUUNEeeJkrA3PIO9Tw" type="3027" element="_Zt_k_kUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzBkUNEeeJkrA3PIO9Tw" type="5017" element="_Zt_k_kUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzB0UNEeeJkrA3PIO9Tw" x="784" y="123" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAzCEUNEeeJkrA3PIO9Tw" type="3027" element="_Zt_lDUUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzCUUNEeeJkrA3PIO9Tw" type="5017" element="_Zt_lDUUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzCkUNEeeJkrA3PIO9Tw" x="299" y="15" width="139" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZuAzC0UNEeeJkrA3PIO9Tw" type="3027" element="_Zt_lQ0UNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzDEUNEeeJkrA3PIO9Tw" type="5017" element="_Zt_lQ0UNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzDUUNEeeJkrA3PIO9Tw" x="499" y="124" width="148" height="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZuAzDkUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzD0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ZuAzEEUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ZuAzEUUNEeeJkrA3PIO9Tw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzEkUNEeeJkrA3PIO9Tw" x="45" y="435" width="1358" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZuAzE0UNEeeJkrA3PIO9Tw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzFEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ZuAzFUUNEeeJkrA3PIO9Tw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ZuAzFkUNEeeJkrA3PIO9Tw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZuAzF0UNEeeJkrA3PIO9Tw" width="1230" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_ZuAzGEUNEeeJkrA3PIO9Tw"/>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzGUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL7kUNEeeJkrA3PIO9Tw" source="_ZuAMWkUNEeeJkrA3PIO9Tw" target="_ZuAMXkUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzGkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL7kUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzG0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzHEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzHUUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzHkUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL8UUNEeeJkrA3PIO9Tw" source="_ZuAMXkUNEeeJkrA3PIO9Tw" target="_ZuAMYkUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzH0UNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL8UUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzIEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzIUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzIkUNEeeJkrA3PIO9Tw" points="[-2, -3, -164, 1]$[164, 10, 2, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzI0UNEeeJkrA3PIO9Tw" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzJEUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL9UUNEeeJkrA3PIO9Tw" source="_ZuAMYkUNEeeJkrA3PIO9Tw" target="_ZuAMZkUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzJUUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL9UUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzJkUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzJ0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzKEUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzKUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL-EUNEeeJkrA3PIO9Tw" source="_ZuAMakUNEeeJkrA3PIO9Tw" target="_ZuAMbUUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzKkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL-EUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzK0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzLEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzLUUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzLkUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL-0UNEeeJkrA3PIO9Tw" source="_ZuAMbUUNEeeJkrA3PIO9Tw" target="_ZuAMcEUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzL0UNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL-0UNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzMEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzMUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzMkUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzM0UNEeeJkrA3PIO9Tw" type="4001" element="_ZuAL_kUNEeeJkrA3PIO9Tw" source="_ZuAMcEUNEeeJkrA3PIO9Tw" target="_ZuAy80UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzNEUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAL_kUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzNUUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzNkUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzN0UNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzOEUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMAUUNEeeJkrA3PIO9Tw" source="_ZuAMc0UNEeeJkrA3PIO9Tw" target="_ZuAMd0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzOUUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMAUUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzOkUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzO0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzPEUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzPUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMBEUNEeeJkrA3PIO9Tw" source="_ZuAMXkUNEeeJkrA3PIO9Tw" target="_ZuAMc0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzPkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMBEUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzP0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzQEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzQUUNEeeJkrA3PIO9Tw" points="[-26, -23, -878, -2]$[-26, -65, -878, -44]$[852, -65, 0, -44]$[852, -27, 0, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzQkUNEeeJkrA3PIO9Tw" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzQ0UNEeeJkrA3PIO9Tw" id="(0.4883720930232558,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzREUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMB0UNEeeJkrA3PIO9Tw" source="_ZuAMXkUNEeeJkrA3PIO9Tw" target="_ZuAMe0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzRUUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMB0UNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzRkUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzR0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzSEUNEeeJkrA3PIO9Tw" points="[0, 22, -1, -86]$[0, 78, -1, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzSUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMC0UNEeeJkrA3PIO9Tw" source="_ZuAMe0UNEeeJkrA3PIO9Tw" target="_ZuAy8EUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzSkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMC0UNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzS0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzTEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzTUUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzTkUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMDkUNEeeJkrA3PIO9Tw" source="_ZuAy_kUNEeeJkrA3PIO9Tw" target="_ZuAzAUUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzT0UNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMDkUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzUEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzUUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzUkUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzU0UNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMEUUNEeeJkrA3PIO9Tw" source="_ZuAzAUUNEeeJkrA3PIO9Tw" target="_ZuAzCEUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzVEUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMEUUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzVUUNEeeJkrA3PIO9Tw" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzVkUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzV0UNEeeJkrA3PIO9Tw" points="[-22, -30, 0, 87]$[-22, -82, 0, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzWEUNEeeJkrA3PIO9Tw" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzWUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMFkUNEeeJkrA3PIO9Tw" source="_ZuAzAUUNEeeJkrA3PIO9Tw" target="_ZuAzC0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzWkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMFkUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzW0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzXEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzXUUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzXkUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMGUUNEeeJkrA3PIO9Tw" source="_ZuAzBUUNEeeJkrA3PIO9Tw" target="_ZuAMc0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzX0UNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMGUUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzYEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzYUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzYkUNEeeJkrA3PIO9Tw" points="[0, 0, -124, 489]$[107, 0, -17, 489]$[107, -486, -17, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzY0UNEeeJkrA3PIO9Tw" id="(1.0,0.4142857142857143)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzZEUNEeeJkrA3PIO9Tw" id="(0.8372093023255814,0.8604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzZUUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMHEUNEeeJkrA3PIO9Tw" source="_ZuAy8EUNEeeJkrA3PIO9Tw" target="_ZuAy_kUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzZkUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMHEUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzZ0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzaEUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzaUUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzakUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMH0UNEeeJkrA3PIO9Tw" source="_ZuAzCEUNEeeJkrA3PIO9Tw" target="_ZuAMZkUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAza0UNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMH0UNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzbEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzbUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzbkUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzb0UNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMIkUNEeeJkrA3PIO9Tw" source="_ZuAzC0UNEeeJkrA3PIO9Tw" target="_ZuAzBUUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzcEUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMIkUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzcUUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzckUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzc0UNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAzdEUNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMJUUNEeeJkrA3PIO9Tw" source="_ZuAMZkUNEeeJkrA3PIO9Tw" target="_ZuAMakUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzdUUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMJUUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzdkUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzd0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzeEUNEeeJkrA3PIO9Tw" points="[0, -6, -58, 0]$[47, -7, -11, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzeUUNEeeJkrA3PIO9Tw" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZuAzekUNEeeJkrA3PIO9Tw" id="(0.09166666666666666,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZuAze0UNEeeJkrA3PIO9Tw" type="4001" element="_ZuAMKEUNEeeJkrA3PIO9Tw" source="_ZuAy80UNEeeJkrA3PIO9Tw" target="_ZuAMc0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZuAzfEUNEeeJkrA3PIO9Tw" type="6001" element="_ZuAMKEUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZuAzfUUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZuAzfkUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZuAzf0UNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
