<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_XflzkEUNEeeJkrA3PIO9Tw" name="Example-ModifyPendingVacationRequest" version="1.5.0" author="antoine" bonitaVersion="7.10.3" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E33">
    <elements xmi:type="process:Pool" xmi:id="_XflzkUUNEeeJkrA3PIO9Tw" documentation="This process will retrieve the user selected vacation request to edit, then retrieve the vacation available, then update vacation available according to delta between current and new version of the request and finally update the existing vacation request." name="Modify Pending Vacation Request" version="1.5.0" displayName="Modify pending vacation request">
      <elements xmi:type="process:Lane" xmi:id="_XflzkkUNEeeJkrA3PIO9Tw" name="Requester lane" actor="_Xfl0aUUNEeeJkrA3PIO9Tw">
        <elements xmi:type="process:StartEvent" xmi:id="_Xflzk0UNEeeJkrA3PIO9Tw" name="Start modify" outgoing="_Xfl0ZkUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XflzlUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XflzlkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xflzl0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XflzmEUNEeeJkrA3PIO9Tw" name="Update vacation available" outgoing="_Xfl0XUUNEeeJkrA3PIO9Tw" incoming="_Xfl0ZkUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XflzmkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xflzm0UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XflznEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_XflznUUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XflznkUNEeeJkrA3PIO9Tw" name="vacationAvailable" content="vacationAvailable" type="TYPE_VARIABLE" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMleWsNmEemUnogr5zNDiA" name="vacationAvailable" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XflzoEUNEeeJkrA3PIO9Tw" name="VacationAvailable.findByBonitaUserId" content="SELECT v&#xA;FROM VacationAvailable v&#xA;WHERE v.bonitaUserId= :bonitaUserId&#xA;" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="expression:Expression" xmi:id="_ulGD0NreEemWoPaj1w4E3A" name="bonitaUserId" content="bonitaUserId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_ulGD0dreEemWoPaj1w4E3A" name="processInstanceInitiatorUserId" content="BonitaUsers.getProcessInstanceInitiator(apiAccessor,processInstanceId).id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_ulGD0treEemWoPaj1w4E3A" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_ulGD09reEemWoPaj1w4E3A" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </referencedElements>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XflzpEUNEeeJkrA3PIO9Tw" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_XflzpUUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XflzpkUNEeeJkrA3PIO9Tw" name="vacationAvailable" content="vacationAvailable" type="TYPE_VARIABLE" returnType="com.company.model.VacationAvailable">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMleYcNmEemUnogr5zNDiA" name="vacationAvailable" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XflzqEUNEeeJkrA3PIO9Tw" name="calculateNewDaysAvailableCounter" content="vacationAvailable.daysAvailableCounter +&#xD;&#xA;vacationRequest.numberOfDays - vacationRequestModification.numberOfDays" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3hD5QNreEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMleY8NmEemUnogr5zNDiA" name="vacationAvailable" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMleZcNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XflzrEUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setDaysAvailableCounter">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XflzrUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XflzrkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xflzr0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XflzsEUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XflzsUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XflzskUNEeeJkrA3PIO9Tw" name="Update vacation request" outgoing="_Xfl0YEUNEeeJkrA3PIO9Tw" incoming="_Xfl0XUUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XflztEUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XflztUUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XflztkUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Xflzt0UNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XflzuEUNEeeJkrA3PIO9Tw" name="vacationRequest" content="vacationRequest" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMleaMNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XflzukUNEeeJkrA3PIO9Tw" name="numberOfDays" content="vacationRequestModification.numberOfDays" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_D4cssNrfEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XflzvEUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setNumberOfDays">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_XflzvUUNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XflzvkUNEeeJkrA3PIO9Tw" name="vacationRequest" content="vacationRequest" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMlebcNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XflzwEUNEeeJkrA3PIO9Tw" name="startDate" content="vacationRequestModification.startDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HLwQgNrfEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XflzwkUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setStartDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Xflzw0UNEeeJkrA3PIO9Tw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XflzxEUNEeeJkrA3PIO9Tw" name="vacationRequest" content="vacationRequest" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMlecsNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XflzxkUNEeeJkrA3PIO9Tw" name="returnDate" content="vacationRequestModification.returnDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_J6BNkNrfEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_XflzyEUNEeeJkrA3PIO9Tw" type="JAVA_METHOD" expression="setReturnDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Mzf8INrfEemWoPaj1w4E3A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Mzf8IdrfEemWoPaj1w4E3A" name="vacationRequestModification" content="vacationRequestModification" type="TYPE_VARIABLE" returnType="com.company.model.VacationRequest">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_NxLsYNrfEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Mzf8ItrfEemWoPaj1w4E3A" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_Mzf8I9rfEemWoPaj1w4E3A" type="DELETION"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XflzyUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XflzykUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xflzy0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XflzzEUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XflzzUUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_XflzzkUNEeeJkrA3PIO9Tw" name="End modify" incoming="_Xfl0Y0UNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xflz0EUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xflz0UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xflz0kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xflz00UNEeeJkrA3PIO9Tw" name="Update calendar" outgoing="_Xfl0Y0UNEeeJkrA3PIO9Tw" incoming="_Xfl0YEUNEeeJkrA3PIO9Tw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xflz1UUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xflz1kUNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xflz10UNEeeJkrA3PIO9Tw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_-CX80EqzEeeZ-cvVQD6SQA" name="calUpdateEventDetails" definitionId="google-calendar-v3-update-event" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-CX80UqzEeeZ-cvVQD6SQA" definitionId="google-calendar-v3-update-event" version="1.0.0" modelVersion="7.1.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX80kqzEeeZ-cvVQD6SQA" key="applicationName">
                <expression xmi:type="expression:Expression" xmi:id="_-CX800qzEeeZ-cvVQD6SQA" name="calendarApplicationName" content="calendarApplicationName" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_-CX81EqzEeeZ-cvVQD6SQA" name="calendarApplicationName" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX81UqzEeeZ-cvVQD6SQA" key="serviceAccountId">
                <expression xmi:type="expression:Expression" xmi:id="_-CX81kqzEeeZ-cvVQD6SQA" name="calendarServiceAccountId" content="calendarServiceAccountId" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_-CX810qzEeeZ-cvVQD6SQA" name="calendarServiceAccountId" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX82EqzEeeZ-cvVQD6SQA" key="serviceAccountP12File">
                <expression xmi:type="expression:Expression" xmi:id="_-CX82UqzEeeZ-cvVQD6SQA" name="calendarServiceAccountP12File" content="calendarServiceAccountP12File" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_-CX82kqzEeeZ-cvVQD6SQA" name="calendarServiceAccountP12File" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX820qzEeeZ-cvVQD6SQA" key="serviceAccountUser">
                <expression xmi:type="expression:Expression" xmi:id="_-CX83EqzEeeZ-cvVQD6SQA" name="calendarServiceAccountUser" content="calendarServiceAccountUser" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_-CX83UqzEeeZ-cvVQD6SQA" name="calendarServiceAccountUser" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX83kqzEeeZ-cvVQD6SQA" key="calendarId">
                <expression xmi:type="expression:Expression" xmi:id="_-CX830qzEeeZ-cvVQD6SQA" name="calendarCalendarId" content="calendarCalendarId" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_-CX84EqzEeeZ-cvVQD6SQA" name="calendarCalendarId" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX84UqzEeeZ-cvVQD6SQA" key="maxAttendees">
                <expression xmi:type="expression:Expression" xmi:id="_-CX84kqzEeeZ-cvVQD6SQA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX840qzEeeZ-cvVQD6SQA" key="sendNotifications">
                <expression xmi:type="expression:Expression" xmi:id="_-CX85EqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX85UqzEeeZ-cvVQD6SQA" key="prettyPrint">
                <expression xmi:type="expression:Expression" xmi:id="_-CX85kqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX850qzEeeZ-cvVQD6SQA" key="startDate">
                <expression xmi:type="expression:Expression" xmi:id="_-CX86EqzEeeZ-cvVQD6SQA" name="formatStartDate" content="vacationRequest.startDate.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMmFnsNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX86kqzEeeZ-cvVQD6SQA" key="startTime">
                <expression xmi:type="expression:Expression" xmi:id="_-CX860qzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX87EqzEeeZ-cvVQD6SQA" key="startTimeZone">
                <expression xmi:type="expression:Expression" xmi:id="_-CX87UqzEeeZ-cvVQD6SQA" name="UTC" content="UTC" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX87kqzEeeZ-cvVQD6SQA" key="endDate">
                <expression xmi:type="expression:Expression" xmi:id="_-CX870qzEeeZ-cvVQD6SQA" name="formatReturnDate" content="vacationRequest.returnDate.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMmFosNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX88UqzEeeZ-cvVQD6SQA" key="endTime">
                <expression xmi:type="expression:Expression" xmi:id="_-CX88kqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX880qzEeeZ-cvVQD6SQA" key="endTimeZone">
                <expression xmi:type="expression:Expression" xmi:id="_-CX89EqzEeeZ-cvVQD6SQA" name="UTC" content="UTC" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX89UqzEeeZ-cvVQD6SQA" key="allDay">
                <expression xmi:type="expression:Expression" xmi:id="_-CX89kqzEeeZ-cvVQD6SQA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX890qzEeeZ-cvVQD6SQA" key="description">
                <expression xmi:type="expression:Expression" xmi:id="_-CX8-EqzEeeZ-cvVQD6SQA" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX8-UqzEeeZ-cvVQD6SQA" key="location">
                <expression xmi:type="expression:Expression" xmi:id="_-CX8-kqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX8-0qzEeeZ-cvVQD6SQA" key="summary">
                <expression xmi:type="expression:Expression" xmi:id="_-CX8_EqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX8_UqzEeeZ-cvVQD6SQA" key="anyoneCanAddSelf">
                <expression xmi:type="expression:Expression" xmi:id="_-CX8_kqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX8_0qzEeeZ-cvVQD6SQA" key="attendeesEmails">
                <expression xmi:type="expression:ListExpression" xmi:id="_-CX9AEqzEeeZ-cvVQD6SQA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9AUqzEeeZ-cvVQD6SQA" key="colorId">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9AkqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9A0qzEeeZ-cvVQD6SQA" key="gadgetDisplay">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9BEqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9BUqzEeeZ-cvVQD6SQA" key="gadgetHeight">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9BkqzEeeZ-cvVQD6SQA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9B0qzEeeZ-cvVQD6SQA" key="gadgetIconLink">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9CEqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9CUqzEeeZ-cvVQD6SQA" key="gadgetLink">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9CkqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9C0qzEeeZ-cvVQD6SQA" key="gadgetPreferences">
                <expression xmi:type="expression:TableExpression" xmi:id="_-CX9DEqzEeeZ-cvVQD6SQA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9DUqzEeeZ-cvVQD6SQA" key="gadgetTitle">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9DkqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9D0qzEeeZ-cvVQD6SQA" key="gadgetType">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9EEqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9EUqzEeeZ-cvVQD6SQA" key="gadgetWidth">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9EkqzEeeZ-cvVQD6SQA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9E0qzEeeZ-cvVQD6SQA" key="guestsCanInviteOthers">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9FEqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9FUqzEeeZ-cvVQD6SQA" key="guestsCanSeeOtherGuests">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9FkqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9F0qzEeeZ-cvVQD6SQA" key="id">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9GEqzEeeZ-cvVQD6SQA" name="vacationRequest - com.company.model.VacationRequest#getCalendarEventId" content="getCalendarEventId" type="TYPE_JAVA_METHOD_CALL" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QMmsdMNmEemUnogr5zNDiA" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9GkqzEeeZ-cvVQD6SQA" key="originalStartDate">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9G0qzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9HEqzEeeZ-cvVQD6SQA" key="originalStartTime">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9HUqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9HkqzEeeZ-cvVQD6SQA" key="originalStartTimeZone">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9H0qzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9IEqzEeeZ-cvVQD6SQA" key="recurrence">
                <expression xmi:type="expression:ListExpression" xmi:id="_-CX9IUqzEeeZ-cvVQD6SQA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9IkqzEeeZ-cvVQD6SQA" key="reminderOverrides">
                <expression xmi:type="expression:ListExpression" xmi:id="_-CX9I0qzEeeZ-cvVQD6SQA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9JEqzEeeZ-cvVQD6SQA" key="reminderUseDefault">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9JUqzEeeZ-cvVQD6SQA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9JkqzEeeZ-cvVQD6SQA" key="sequence">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9J0qzEeeZ-cvVQD6SQA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9KEqzEeeZ-cvVQD6SQA" key="sourceTitle">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9KUqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9KkqzEeeZ-cvVQD6SQA" key="sourceUrl">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9K0qzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9LEqzEeeZ-cvVQD6SQA" key="status">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9LUqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9LkqzEeeZ-cvVQD6SQA" key="transparency">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9L0qzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-CX9MEqzEeeZ-cvVQD6SQA" key="visibility">
                <expression xmi:type="expression:Expression" xmi:id="_-CX9MUqzEeeZ-cvVQD6SQA" content="" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xfl0OkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xfl0O0UNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xfl0PEUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xfl0PUUNEeeJkrA3PIO9Tw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xfl0PkUNEeeJkrA3PIO9Tw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Xfl0QUUNEeeJkrA3PIO9Tw" name="vacationRequest" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest">
        <defaultValue xmi:type="expression:Expression" xmi:id="_sXJ6MEthEeey8-nS6o05Dw" name="VacationRequest.findByPersistenceId" content="SELECT v&#xA;FROM VacationRequest v&#xA;WHERE v.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.VacationRequest">
          <referencedElements xmi:type="expression:Expression" xmi:id="_sXJ6MUthEeey8-nS6o05Dw" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_sXJ6MkthEeey8-nS6o05Dw" name="toLongValue" content="Long.valueOf(vacationRequestIdContract)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_QMleecNmEemUnogr5zNDiA" name="vacationRequestIdContract" description="The id of the edited vacation request.">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_QMmsgcNmEemUnogr5zNDiA"/>
              </referencedElements>
            </referencedElements>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Xfl0R0UNEeeJkrA3PIO9Tw" name="vacationAvailable" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationAvailable">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Xfl0SEUNEeeJkrA3PIO9Tw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6yKTENrdEemWoPaj1w4E3A" documentation="Temporarily store the information of the desired change on the existing vacation request. We need to store such information in order to be able to run the sequence of actions (retrieve first, update second) in the appropriate order." name="vacationRequestModification" dataType="_Xfl0j0UNEeeJkrA3PIO9Tw" className="com.company.model.VacationRequest">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6yKTEdrdEemWoPaj1w4E3A" name="init_vacationRequestModification()" content="import com.company.model.VacationRequest&#xA;&#xA;new VacationRequest(startDate: startDateContract,&#xA;&#x9;returnDate: returnDateContract,&#xA;&#x9;numberOfDays: numberOfDaysContract,&#xA;&#x9;status: 'temporary - request modification',&#xA;&#x9;newRequestProcessInstanceId: processInstanceId,&#xA;&#x9;requesterBonitaUserId: BonitaUsers.getProcessInstanceInitiator(apiAccessor,processInstanceId).id)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.VacationRequest">
          <referencedElements xmi:type="expression:Expression" xmi:id="_CP6CMN9sEemSy--XEK5KCw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_aIakQNreEemWoPaj1w4E3A" name="startDateContract" type="LOCALDATE" description="The new value for the first day of vacation.">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_aIakQdreEemWoPaj1w4E3A"/>
          </referencedElements>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_aIakQtreEemWoPaj1w4E3A" name="numberOfDaysContract" type="INTEGER" description="The new value for the number of days of vacation, not including non-working days.">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_aIakQ9reEemWoPaj1w4E3A"/>
          </referencedElements>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_aIbLUNreEemWoPaj1w4E3A" name="returnDateContract" type="LOCALDATE" description="The new value for the day the requester returns to work.">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_aIbLUdreEemWoPaj1w4E3A"/>
          </referencedElements>
          <referencedElements xmi:type="expression:Expression" xmi:id="_aIbLUtreEemWoPaj1w4E3A" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Xfl0V0UNEeeJkrA3PIO9Tw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_Xfl0WEUNEeeJkrA3PIO9Tw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Xfl0WkUNEeeJkrA3PIO9Tw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_Xfl0W0UNEeeJkrA3PIO9Tw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xfl0XUUNEeeJkrA3PIO9Tw" target="_XflzskUNEeeJkrA3PIO9Tw" source="_XflzmEUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xfl0XkUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xfl0X0UNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xfl0YEUNEeeJkrA3PIO9Tw" target="_Xflz00UNEeeJkrA3PIO9Tw" source="_XflzskUNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xfl0YUUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xfl0YkUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xfl0Y0UNEeeJkrA3PIO9Tw" target="_XflzzkUNEeeJkrA3PIO9Tw" source="_Xflz00UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xfl0ZEUNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xfl0ZUUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xfl0ZkUNEeeJkrA3PIO9Tw" target="_XflzmEUNEeeJkrA3PIO9Tw" source="_Xflzk0UNEeeJkrA3PIO9Tw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xfl0Z0UNEeeJkrA3PIO9Tw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xfl0aEUNEeeJkrA3PIO9Tw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Xfl0aUUNEeeJkrA3PIO9Tw" documentation="Actor who is modifying his vacation request. Only used to defined who can start the process." name="Requester actor" initiator="true"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Xfl0akUNEeeJkrA3PIO9Tw" name="calendarApplicationName" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Xfl0a0UNEeeJkrA3PIO9Tw" name="calendarCalendarId" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Xfl0bEUNEeeJkrA3PIO9Tw" name="calendarServiceAccountId" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Xfl0bUUNEeeJkrA3PIO9Tw" name="calendarServiceAccountP12File" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Xfl0bkUNEeeJkrA3PIO9Tw" name="calendarServiceAccountUser" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_Xfl0b0UNEeeJkrA3PIO9Tw">
        <inputs xmi:type="process:ContractInput" xmi:id="_Xfl0cEUNEeeJkrA3PIO9Tw" name="vacationRequestIdContract" description="The id of the edited vacation request.">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xfl0cUUNEeeJkrA3PIO9Tw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_Xfl0ckUNEeeJkrA3PIO9Tw" name="startDateContract" type="LOCALDATE" description="The new value for the first day of vacation.">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xfl0c0UNEeeJkrA3PIO9Tw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_Xfl0dEUNEeeJkrA3PIO9Tw" name="returnDateContract" type="LOCALDATE" description="The new value for the day the requester returns to work.">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xfl0dUUNEeeJkrA3PIO9Tw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_Xfl0dkUNEeeJkrA3PIO9Tw" name="numberOfDaysContract" type="INTEGER" description="The new value for the number of days of vacation, not including non-working days.">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xfl0d0UNEeeJkrA3PIO9Tw"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xfl0eEUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_Xfl0eUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xfl0ekUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xfl0e0UNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_Xfl0fEUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xfl0fUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xfl0fkUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_Xfl0f0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xfl0gEUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xfl0gUUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_Xfl0gkUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xfl0g0UNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xfl0hEUNEeeJkrA3PIO9Tw">
        <name xmi:type="expression:Expression" xmi:id="_Xfl0hUUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xfl0hkUNEeeJkrA3PIO9Tw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Xfl0h0UNEeeJkrA3PIO9Tw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Xfl0iEUNEeeJkrA3PIO9Tw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Xfl0iUUNEeeJkrA3PIO9Tw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Xfl0ikUNEeeJkrA3PIO9Tw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Xfl0i0UNEeeJkrA3PIO9Tw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Xfl0jEUNEeeJkrA3PIO9Tw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Xfl0jUUNEeeJkrA3PIO9Tw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Xfl0jkUNEeeJkrA3PIO9Tw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Xfl0j0UNEeeJkrA3PIO9Tw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Xfl0kEUNEeeJkrA3PIO9Tw" type="Process" element="_XflzkEUNEeeJkrA3PIO9Tw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Xfl0kUUNEeeJkrA3PIO9Tw" type="2007" element="_XflzkUUNEeeJkrA3PIO9Tw">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0kkUNEeeJkrA3PIO9Tw" type="5008" element="_XflzkUUNEeeJkrA3PIO9Tw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0k0UNEeeJkrA3PIO9Tw" type="7001" element="_XflzkUUNEeeJkrA3PIO9Tw">
        <children xmi:type="notation:Node" xmi:id="_Xfl0lEUNEeeJkrA3PIO9Tw" type="3007" element="_XflzkkUNEeeJkrA3PIO9Tw">
          <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0lUUNEeeJkrA3PIO9Tw" type="5007" element="_XflzkkUNEeeJkrA3PIO9Tw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0lkUNEeeJkrA3PIO9Tw" type="7002" element="_XflzkkUNEeeJkrA3PIO9Tw">
            <children xmi:type="notation:Shape" xmi:id="_Xfl0l0UNEeeJkrA3PIO9Tw" type="3002" element="_Xflzk0UNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0mEUNEeeJkrA3PIO9Tw" visible="false" type="5024" element="_Xflzk0UNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xfl0mUUNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0mkUNEeeJkrA3PIO9Tw" x="60" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xfl0m0UNEeeJkrA3PIO9Tw" type="3027" element="_XflzmEUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0nEUNEeeJkrA3PIO9Tw" type="5017" element="_XflzmEUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0nUUNEeeJkrA3PIO9Tw" x="177" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xfl0nkUNEeeJkrA3PIO9Tw" type="3027" element="_XflzskUNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0n0UNEeeJkrA3PIO9Tw" type="5017" element="_XflzskUNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0oEUNEeeJkrA3PIO9Tw" x="367" y="95" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xfl0oUUNEeeJkrA3PIO9Tw" type="3062" element="_XflzzkUNEeeJkrA3PIO9Tw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0okUNEeeJkrA3PIO9Tw" visible="false" type="5090" element="_XflzzkUNEeeJkrA3PIO9Tw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xfl0o0UNEeeJkrA3PIO9Tw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0pEUNEeeJkrA3PIO9Tw" x="747" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xfl0pUUNEeeJkrA3PIO9Tw" type="3027" element="_Xflz00UNEeeJkrA3PIO9Tw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0pkUNEeeJkrA3PIO9Tw" type="5017" element="_Xflz00UNEeeJkrA3PIO9Tw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0p0UNEeeJkrA3PIO9Tw" x="576" y="96" width="116" height="58"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Xfl0qEUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Xfl0qUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Xfl0qkUNEeeJkrA3PIO9Tw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Xfl0q0UNEeeJkrA3PIO9Tw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0rEUNEeeJkrA3PIO9Tw"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Xfl0rUUNEeeJkrA3PIO9Tw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xfl0rkUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Xfl0r0UNEeeJkrA3PIO9Tw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Xfl0sEUNEeeJkrA3PIO9Tw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xfl0sUUNEeeJkrA3PIO9Tw" width="930" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Xfl0skUNEeeJkrA3PIO9Tw"/>
    <edges xmi:type="notation:Connector" xmi:id="_Xfl0s0UNEeeJkrA3PIO9Tw" type="4001" element="_Xfl0XUUNEeeJkrA3PIO9Tw" source="_Xfl0m0UNEeeJkrA3PIO9Tw" target="_Xfl0nkUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0tEUNEeeJkrA3PIO9Tw" type="6001" element="_Xfl0XUUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xfl0tUUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xfl0tkUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xfl0t0UNEeeJkrA3PIO9Tw" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xfl0uEUNEeeJkrA3PIO9Tw" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xfl0uUUNEeeJkrA3PIO9Tw" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xfl0ukUNEeeJkrA3PIO9Tw" type="4001" element="_Xfl0YEUNEeeJkrA3PIO9Tw" source="_Xfl0nkUNEeeJkrA3PIO9Tw" target="_Xfl0pUUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xfl0u0UNEeeJkrA3PIO9Tw" type="6001" element="_Xfl0YEUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XfmaoEUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XfmaoUUNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XfmaokUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xfmao0UNEeeJkrA3PIO9Tw" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XfmapEUNEeeJkrA3PIO9Tw" type="4001" element="_Xfl0Y0UNEeeJkrA3PIO9Tw" source="_Xfl0pUUNEeeJkrA3PIO9Tw" target="_Xfl0oUUNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XfmapUUNEeeJkrA3PIO9Tw" type="6001" element="_Xfl0Y0UNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XfmapkUNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xfmap0UNEeeJkrA3PIO9Tw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XfmaqEUNEeeJkrA3PIO9Tw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XfmaqUUNEeeJkrA3PIO9Tw" type="4001" element="_Xfl0ZkUNEeeJkrA3PIO9Tw" source="_Xfl0l0UNEeeJkrA3PIO9Tw" target="_Xfl0m0UNEeeJkrA3PIO9Tw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XfmaqkUNEeeJkrA3PIO9Tw" type="6001" element="_Xfl0ZkUNEeeJkrA3PIO9Tw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xfmaq0UNEeeJkrA3PIO9Tw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XfmarEUNEeeJkrA3PIO9Tw" fontName="DejaVu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XfmarUUNEeeJkrA3PIO9Tw" points="[0, -15, -244, 4]$[238, -20, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XfmarkUNEeeJkrA3PIO9Tw" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xfmar0UNEeeJkrA3PIO9Tw" id="(0.05,0.4166666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
